baseURL = 'https://unionsep.github.io/'
languageCode = 'en-us'
title = 'notes'
theme = "hermit-v2"
publishDir = "docs"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[languages]
  [languages.en]
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    [languages.en.params]
      homeSubtitle = "Hope for the best, and prepare for the worst."

[params]
  dateform = "Jan 2, 2006"
  dateformShort = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  homeSubtitlePrinter = true
  scrollToTop = true
  
  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/unionsep"
  [[params.socialLinks]]
    name = "twitter"
    url = "https://x.com/unionSep"
  [[params.socialLinks]]
    name = "email"
    url = "mailto:union.septem@gmail.com"

  [params.author]
    name = "unionsep"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10
